services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    user: "1000:1000"
    volumes:
      - db_data:/data
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SERVICE_ACCOUNT_USERNAME=${SERVICE_ACCOUNT_USERNAME}
      - SERVICE_ACCOUNT_PASSWORD=${SERVICE_ACCOUNT_PASSWORD}
      - LDAP_URL=${LDAP_URL:-ad.unil.ch}
      - LDAP_PORT=${LDAP_PORT:-636}
      - LDAP_BASE_DN=${LDAP_BASE_DN:-DC=ad,DC=unil,DC=ch}
      - RATE_LIMIT_MAX_ATTEMPTS=${RATE_LIMIT_MAX_ATTEMPTS:-5}
      - RATE_LIMIT_WINDOW_MINUTES=${RATE_LIMIT_WINDOW_MINUTES:-1}
      # - SEED_DEV_DATA=true

volumes:
  db_data:
