services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data/data.db:/app/database/data.db
      - sqlite_data:/app/database

volumes:
  sqlite_data:
