name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  sqlite3: ^2.7.3
  dartdap: ^0.9.1
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.17.0
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  asn1lib: ^1.5.9
  basic_utils: ^5.7.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
